name: Hello World

on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

jobs:
  test_1:
    run-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Hello Test"
